//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBirthdayAlarmBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBirthdayAlarmBot.Resources.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Action canceled..
        /// </summary>
        internal static string ActionCancelled {
            get {
                return ResourceManager.GetString("ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;code&gt;/addbirthday @username MMMM d, yyyy&lt;/code&gt;..
        /// </summary>
        internal static string AddBirthdayByUsernameFormat {
            get {
                return ResourceManager.GetString("AddBirthdayByUsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/addbirthday&lt;/pre&gt; then, for example, &lt;pre&gt;May 25, 2002&lt;/pre&gt; or without a year &lt;pre&gt;May 25&lt;/pre&gt; or directly &lt;pre&gt;/addbirthday June 1, 2000&lt;/pre&gt; or directly without a year &lt;pre&gt;/addbirthday June 1&lt;/pre&gt; to add your birthday..
        /// </summary>
        internal static string AddbirthdayCommandHelp {
            get {
                return ResourceManager.GetString("AddbirthdayCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚫 Only group owner and bot admins can add birthdays of other users..
        /// </summary>
        internal static string AddBirthdayOfOtherUserAdminOnly {
            get {
                return ResourceManager.GetString("AddBirthdayOfOtherUserAdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/addbirthday @username date&lt;/pre&gt; where date is any parseable date, such as &lt;pre&gt;May 25, 2002&lt;/pre&gt; or without a year &lt;pre&gt;May 25&lt;/pre&gt; to add the specified user&apos;s birthday (admins only)..
        /// </summary>
        internal static string AddbirthdayOfOtherUserCommandHelp {
            get {
                return ResourceManager.GetString("AddbirthdayOfOtherUserCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your birthday, for example &lt;code&gt;May 25, 2002&lt;/code&gt; or without a year &lt;code&gt;May 25&lt;/code&gt;:.
        /// </summary>
        internal static string AddBirthdayStep1 {
            get {
                return ResourceManager.GetString("AddBirthdayStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or use &lt;code&gt;/cancel&lt;/code&gt; to cancel..
        /// </summary>
        internal static string AddBirthdayStep2InvalidDateAppendix {
            get {
                return ResourceManager.GetString("AddBirthdayStep2InvalidDateAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Birthday added for {0}..
        /// </summary>
        internal static string AddBirthdaySuccess {
            get {
                return ResourceManager.GetString("AddBirthdaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, happy birthday! 🎉.
        /// </summary>
        internal static string BirthdayCongrats {
            get {
                return ResourceManager.GetString("BirthdayCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ No birthday to remove..
        /// </summary>
        internal static string BirthdayNotFound {
            get {
                return ResourceManager.GetString("BirthdayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your birthday.
        /// </summary>
        internal static string BotCommandAddBirthday {
            get {
                return ResourceManager.GetString("BotCommandAddBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your birthday or another user&apos;s birthday.
        /// </summary>
        internal static string BotCommandAddBirthdayAdmin {
            get {
                return ResourceManager.GetString("BotCommandAddBirthdayAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel birthday adding operation.
        /// </summary>
        internal static string BotCommandCancel {
            get {
                return ResourceManager.GetString("BotCommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command formats and tips.
        /// </summary>
        internal static string BotCommandHelp {
            get {
                return ResourceManager.GetString("BotCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command formats (including admin commands) and tips.
        /// </summary>
        internal static string BotCommandHelpAdmin {
            get {
                return ResourceManager.GetString("BotCommandHelpAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all birthdays.
        /// </summary>
        internal static string BotCommandList {
            get {
                return ResourceManager.GetString("BotCommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your birthday.
        /// </summary>
        internal static string BotCommandRemoveBirthday {
            get {
                return ResourceManager.GetString("BotCommandRemoveBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your birthday or another user&apos;s birthday.
        /// </summary>
        internal static string BotCommandRemoveBirthdayAdmin {
            get {
                return ResourceManager.GetString("BotCommandRemoveBirthdayAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the birthday congratulations language.
        /// </summary>
        internal static string BotCommandSetCongratulateLangOwner {
            get {
                return ResourceManager.GetString("BotCommandSetCongratulateLangOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/cancel&lt;/pre&gt;for canceling the birthday addition operation..
        /// </summary>
        internal static string CancelCommandHelp {
            get {
                return ResourceManager.GetString("CancelCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎈 Choose the language for the congratulatory messages:.
        /// </summary>
        internal static string ChooseCongratulateLang {
            get {
                return ResourceManager.GetString("ChooseCongratulateLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Congratulations language set to {0}..
        /// </summary>
        internal static string CongratulationsLanguageChanged {
            get {
                return ResourceManager.GetString("CongratulationsLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Already added..
        /// </summary>
        internal static string DuplicatedUserMessage {
            get {
                return ResourceManager.GetString("DuplicatedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😲 Error: sender information is unavailable..
        /// </summary>
        internal static string ErrorMessageFromIsNull {
            get {
                return ResourceManager.GetString("ErrorMessageFromIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Format:.
        /// </summary>
        internal static string FormatPrefix {
            get {
                return ResourceManager.GetString("FormatPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📚 Commands:.
        /// </summary>
        internal static string HelpMessageTitle {
            get {
                return ResourceManager.GetString("HelpMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Invalid date. Enter a date like &lt;code&gt;May 25, 2002&lt;/code&gt; or without a year &lt;code&gt;May 25&lt;/code&gt;..
        /// </summary>
        internal static string InvalidDateWarning {
            get {
                return ResourceManager.GetString("InvalidDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashionably late, Slowpoke edition 😅.
        /// </summary>
        internal static string LateBirthdayCongratsAppendix {
            get {
                return ResourceManager.GetString("LateBirthdayCongratsAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/list&lt;/pre&gt;to display the list of all added birthdays..
        /// </summary>
        internal static string ListCommandHelp {
            get {
                return ResourceManager.GetString("ListCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty..
        /// </summary>
        internal static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM d.
        /// </summary>
        internal static string ListItemDateFormat {
            get {
                return ResourceManager.GetString("ListItemDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎂 Birthday list:.
        /// </summary>
        internal static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ No active actions to cancel..
        /// </summary>
        internal static string NoActiveActionsToCancel {
            get {
                return ResourceManager.GetString("NoActiveActionsToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;code&gt;/removebirthday @username&lt;/code&gt;..
        /// </summary>
        internal static string RemoveBirthdayByUsernameFormat {
            get {
                return ResourceManager.GetString("RemoveBirthdayByUsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/removebirthday&lt;/pre&gt;to remove your birthday..
        /// </summary>
        internal static string RemovebirthdayCommandHelp {
            get {
                return ResourceManager.GetString("RemovebirthdayCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚫 Only group owner and bot admins can remove birthdays of other users..
        /// </summary>
        internal static string RemoveBirthdayOfOtherUserAdminOnly {
            get {
                return ResourceManager.GetString("RemoveBirthdayOfOtherUserAdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;/removebirthday @username&lt;/pre&gt; to remove the specified user&apos;s birthday (admins only)..
        /// </summary>
        internal static string RemovebirthdayOfOtherUserCommandHelp {
            get {
                return ResourceManager.GetString("RemovebirthdayOfOtherUserCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Birthday for {0} removed..
        /// </summary>
        internal static string RemoveBirthdaySuccess {
            get {
                return ResourceManager.GetString("RemoveBirthdaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚫 Only group owner can set congratulate lang..
        /// </summary>
        internal static string SetCongratulateLangOwnerOnly {
            get {
                return ResourceManager.GetString("SetCongratulateLangOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Unsupported language..
        /// </summary>
        internal static string UnsupportedLanguage {
            get {
                return ResourceManager.GetString("UnsupportedLanguage", resourceCulture);
            }
        }
    }
}
